pipeline {
    agent {
        label 'docker-worker-1'
    }

    environment {
        SONAR_HOST_URL = 'http://sonarqube:9000'
        SONAR_TOKEN    = credentials('sonar-token')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Compile') {
            steps {
                dir('sonarqube-java-demo') {
                    sh 'mvn -B clean compile'
                }
            }
        }

        stage('Unit Test and Coverage') {
            steps {
                dir('sonarqube-java-demo') {
                    sh 'mvn -B verify'
                }
            }
            post {
                always {
                    junit allowEmptyResults: true, testResults: 'sonarqube-java-demo/target/surefire-reports/*.xml'
                    archiveArtifacts allowEmptyArchive: true, artifacts: 'sonarqube-java-demo/target/site/jacoco/**'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('sonarqube-java-demo') {
                    withSonarQubeEnv('SonarQube') {
                        sh '''
                            mvn -B sonar:sonar \
                              -Dsonar.projectKey=sonarqube-java-demo \
                              -Dsonar.projectName="SonarQube Java Demo" \
                              -Dsonar.host.url=${SONAR_HOST_URL} \
                              -Dsonar.token=${SONAR_TOKEN}
                        '''
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }

    post {
        always {
            echo 'Build completed.'
        }
    }
}
